package net.bewitchingbiohazard.ranchinexpansionmod.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class CowAnimations {

    public static final AnimationDefinition WALKING_ANIMATION = AnimationDefinition.Builder.withLength(6f).looping()
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.4f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.4f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.4f, -1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(29.91f, 2.35f, 1.26f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-32.71f, 1.04f, -0.91f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.18f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.6f, 0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.6f, -0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(30f, 0.24f, -0.63f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-30f, 0.48f, -1.26f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.14f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.6f, -0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.6f, 0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-30f, 1.8f, -0.76f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(30f, 1.8f, -0.76f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.3f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.4f, -0.7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.4f, 0.3f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(14f, 2f, 7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(14f, 2f, -7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(14f, 2f, -7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(14f, 2f, 7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0.3f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(-0.3f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.8f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(-16f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 1f, 0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 1.2f, 1.5f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(6f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -0.6f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, -0.4f, -1.5f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-3f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition IDLE_ANIMATION = AnimationDefinition.Builder.withLength(6f).looping()
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.2f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(6f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.1f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(13f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.4f, -0.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.posVec(0.2f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.posVec(0.1f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0.07f, -0.1f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(5f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5f, KeyframeAnimations.degreeVec(-5f, 16f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-4.9f, 7.53f, 0.73f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-4.81f, -0.94f, 1.46f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(-0.2f, 0.8f, 1.1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(9f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.3f, -0.9f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(-6f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("Body",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, -0.1f, -0.1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition EAT_ANIMATION = AnimationDefinition.Builder.withLength(12.04167f)
        .addAnimation("Legs",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Legs",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.3f, -0.7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, 0.3f, -0.7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(7f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(7f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.2f, 0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, 0.2f, 0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(18f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(18f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-7f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(-7f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.4f, -1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, 0.4f, -1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-7.94f, 1.06f, 0.83f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(-7.94f, 1.06f, 0.83f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.scaleVec(1f, 1.3f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.scaleVec(1f, 1.3f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, -5.1f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, -5.1f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(44f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(44f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0.1f, -7.1f, -0.3f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0.1f, -7.1f, -0.3f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12.04167f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Ring",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(27f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(27f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12.04167f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0.3f, 0f, -0.6f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0.1f, 0.65f, -0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(-0.1f, 0.6f, -1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0.3f, 0.4f, -0.6f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(2.73f, 12.4f, -6.37f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(31.6f, 1.18f, 2.34f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(22.46f, -10.04f, 11.05f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(35.73f, 12.4f, -6.37f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(-0.1f, 0.4f, 2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(-0.2f, 1.4f, 2.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(-0.2f, 1.4f, 2.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(10.5f, KeyframeAnimations.posVec(-0.1f, 0.3f, 2.3f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tag",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(47f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(47f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, -2.5f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, -2.5f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Bell",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(14f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(14f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Body",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, -1.2f, -1.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, -1.2f, -1.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(11f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(11f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Neck",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, -0.7f, 2.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, -0.7f, 2.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Neck",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(32f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(32f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("BottomJaw",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(5f, KeyframeAnimations.posVec(0f, -0.1f, 0.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(7f,KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(8f, KeyframeAnimations.posVec(0f, -0.1f, 0.2f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("BottomJaw",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(5f, KeyframeAnimations.degreeVec(11f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(8f, KeyframeAnimations.degreeVec(11f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(9f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR))).build();
}
