package net.bewitchingbiohazard.ranchinexpansionmod.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationsDefinitions {


    public static final AnimationDefinition WALKING_ANIMATION = AnimationDefinition.Builder.withLength(6f).looping()
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0.4f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.4f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.4f, -1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(29.91f, 2.35f, 1.26f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-32.71f, 1.04f, -0.91f),
                 AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Left",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.18f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.6f, 0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.6f, -0.8f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                 AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(30f, 0.24f, -0.63f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(-30f, 0.48f, -1.26f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Right",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.14f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.6f, -0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.6f, 0.4f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-30f, 1.8f, -0.76f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(30f, 1.8f, -0.76f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("F_Left",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.3f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0.4f, -0.7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0.4f, 0.3f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("B_Right",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
		    new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
             AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("L_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(14f, 2f, 7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(14f, 2f, -7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("R_Ear",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(14f, 2f, -7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(14f, 2f, 7f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f,KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
		    new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.posVec(0.3f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.posVec(-0.3f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("Tail",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
		    new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
                AnimationChannel.Interpolations.LINEAR),
            new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                AnimationChannel.Interpolations.LINEAR))).build();
}
